version: '3'
services: 
  web:
    container_name: "lavender_web"
    build: .
    volumes:
      - .:/home/lavender/src
    ports:
      - 8001:8001
    environment: 
      - FLASK_APP=/home/lavender/src/run.py
      - FLASK_DEBUG=1
      - ENV=devel 
    command: flask run --host=0.0.0.0 --port=8001